version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.3

    working_directory: ~/ishputra

    steps:
      - checkout

      - run:
          name: Install AWS CLI
          command: pip install awscli --upgrade --user

      - run:
          name: s3 deploy
          command: ~/.local/bin/aws s3 sync --delete --acl public-read ~/ishputra $s3_bucket --exclude ".git/*" --region $s3_region